version: '3.8'

services:
  app:
    build: .
    # volumes:
      # - .:/usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    # environment:
    #   - PYTHONUNBUFFERED=1
volumes:
  .: