# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.event_item import EventItem  # noqa: F401,E501
from swagger_server.database import db
import uuid

class BookItem(db.Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    __tablename__ = 'book_items'
    id = db.Column(db.Integer, primary_key=True)
    booking_code = db.Column(db.String(100), nullable=False, default=str(uuid.uuid4()).replace('-', '').upper())
    registered = db.Column(db.Boolean, nullable=False, default=False)
    user = db.Column(db.String(500), nullable=False)
    # event_id = db.Column(db.Integer, db.ForeignKey('event_item.id'), nullable=False)
    event_id = db.Column('event_id', db.Integer, db.ForeignKey('event_items.id'), nullable=False)

    # event = db.relationship('EventItem', backref=db.backref('book_items', lazy=True))
    event = db.relationship('EventItem', back_populates='book_items')

    # def __init__(self, booking_code, registered, event_id, user):
    #     self.booking_code = booking_code
    #     self.registered = registered
    #     self.user = user
    #     self.event_id = event_id
