# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class GuestItem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, email: str=None, phone: str=None, dni: str=None):  # noqa: E501
        """GuestItem - a model defined in Swagger

        :param name: The name of this GuestItem.  # noqa: E501
        :type name: str
        :param email: The email of this GuestItem.  # noqa: E501
        :type email: str
        :param phone: The phone of this GuestItem.  # noqa: E501
        :type phone: str
        :param dni: The dni of this GuestItem.  # noqa: E501
        :type dni: str
        """
        self.swagger_types = {
            'name': str,
            'email': str,
            'phone': str,
            'dni': str
        }

        self.attribute_map = {
            'name': 'name',
            'email': 'email',
            'phone': 'phone',
            'dni': 'dni'
        }
        self._name = name
        self._email = email
        self._phone = phone
        self._dni = dni

    @classmethod
    def from_dict(cls, dikt) -> 'GuestItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GuestItem of this GuestItem.  # noqa: E501
        :rtype: GuestItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this GuestItem.


        :return: The name of this GuestItem.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this GuestItem.


        :param name: The name of this GuestItem.
        :type name: str
        """

        self._name = name

    @property
    def email(self) -> str:
        """Gets the email of this GuestItem.


        :return: The email of this GuestItem.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this GuestItem.


        :param email: The email of this GuestItem.
        :type email: str
        """

        self._email = email

    @property
    def phone(self) -> str:
        """Gets the phone of this GuestItem.


        :return: The phone of this GuestItem.
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone: str):
        """Sets the phone of this GuestItem.


        :param phone: The phone of this GuestItem.
        :type phone: str
        """

        self._phone = phone

    @property
    def dni(self) -> str:
        """Gets the dni of this GuestItem.


        :return: The dni of this GuestItem.
        :rtype: str
        """
        return self._dni

    @dni.setter
    def dni(self, dni: str):
        """Sets the dni of this GuestItem.


        :param dni: The dni of this GuestItem.
        :type dni: str
        """

        self._dni = dni
